### ISSUE TITLE
Question for Snapshot 04-04-2021

### ISSUE THREAD

**Issue by hawkeyexp** [M1dn1ghtN1nj4/OctoDash_Builds_UNOFFICIAL#1]
Really funny - tody i compiled myselve and same day you released also :-)

But:

i didn't get it managed to connect to octoprint - always initialising - tried with "old" config and after problem i removed it to get the asssitant again but no success - any hints ?

**Comment by M1dn1ghtN1nj4** [comment]
I'm not sure on your setup, but I have a Pi 4 connected to an SKR Mini E3
v2 by a USB cable.

I don't touch my Marlin install at all.

Wipe the Pi sdcard, virgin install of OctoPi 0.18.0 and set wifi settings
in wpa_supplicant.  On first boot, connect to Pi with Putty (terminal
client).  Use my install command for the latest release I built.  Also you
NEED to run through the initial OctoPi setup wizard, or Octodash will never
connect.  When done, pull power from printer (Pi as well).  Reboot.  Power
off.  Reboot again.  This time Octodash setup should work as expected.

**Comment by hawkeyexp** [comment]
hm tried now a clean base setup on a new card - used latest build of octopi (compiled from source so it is upcoming 1.0.0) and used your octoash build on top but no success :-(
Wizard etects octoprint but fails on requesting api key - same as before.
manual config also will fail to connect - crazy...

can you possible show me your working config.json to ensure syntax is same as your working one ?

ps: i use a rpi4, too :-)

**Comment by hawkeyexp** [comment]
seems to be the problem is fixed!

It is a dns error - the server was running with hostname octopi (default) and the new setup of octodash had same name which forced the connection problem - he was requsting the api key from wrong host
